### ISSUE TITLE
Addition of glow and scroll_print methods

### ISSUE THREAD

**Issue by BluePadraig** [pimoroni/fourletter-phat#6]
Hi, 

I've sent a pull request for 2 extra methods:
glow and scroll_print
https://github.com/pimoroni/fourletter-phat/pull/5
It's my first pull request on GitHub, so I hope I've done things right.
Along with the 2 new methods I've added a script example for each of them.
The change log is also updated and the version updated to 0.2.

Refer to the updated documentation for a description of the new methods:
https://github.com/BluePadraig/fourletter-phat/blob/master/documentation/REFERENCE.md

The 2 methods, glow and scroll_print, have been successfully tested on a four letters phat/ Pi Zero W combo.
This is part of a personal Internet Radio project, that uses the four letters phat.

I'll be happy to hear from your comments and ready to proceed to any suggested improvements.

Regards,

BluePadraig

**Comment by Gadgetoid** [comment]
Thank you for these features, scroll_print has definitely been asked about before so I'm sure they'll find some use.

As I mentioned in the pull request, there's no need to worry about versioning because we have tools for that.

Also you should ideally test in Python 2 and 3 since 2 still gets a lot of use on the Pi. I'm terrible at doing this- testing mostly in 2 and just trying to remember what goes awry in 3- so am the worst person to point this out. But it's an ideal :D 

Congrats on your first PR being merged, anyway, and I hope it's the first of many.
